### ISSUE TITLE
Isolate recipe-related builder functions

### ISSUE THREAD

**Issue by redeboer** [ComPWA/tensorwaves#102]
Currently, dictionary keys that depend one the recipe file structure are spreading through the framework. So each time the recipe structure changes, we need to go through the rest of the framework to modify those strings. See e.g. #95.

A first step would be to isolate all builder functionality (e.g. `IntensityBuilder`) to a seperate module, as long as they are dependent on a recipe format.

Related to https://github.com/ComPWA/expertsystem/issues/22

**Comment by spflueger** [comment]
In tensorwaves there is only only the builder which depends on this recipe structure. I don't think this can be improved further until we introduce the recipe class in the expert system as an interface.

**Comment by redeboer** [comment]
> In tensorwaves there is only only the builder which depends on this recipe structure. I don't think this can be improved further until we introduce the recipe class in the expert system as an interface.

That's correct, https://github.com/ComPWA/expertsystem/issues/22 has to be fixed first, but that's a bigger project
