### ISSUE TITLE
Isolate dynamics out from amplitude module

### ISSUE THREAD

**Issue by redeboer** [ComPWA/tensorwaves#162]
For example:
https://github.com/ComPWA/tensorwaves/blob/7c95713a509c3cb0a91e31103fb7d4be7e7ecdc3/src/tensorwaves/physics/helicity_formalism/amplitude.py#L604-L646

is not specific to the helicity formalism and should be placed under a new module like `tensorwaves.physics.dynamics`

**Comment by spflueger** [comment]
Note this is handled with the design change to use sympy expression for the model description #203
