### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by spflueger** [ComPWA/tensorwaves#19]
The setup is analogous to the one of pycomwa. It includes

- [x] testing the installation (fairly simple with pure python now)
- [x] testing code via unittests
- [x] code cov
- [x] code quality tests
- [x] building the docs -> deploy to readthedoc (?) on master branch builds
- [x] setup deploy to pypi on release tag

**[Estimated effort: 1-3 days]**

*Additional problems:*
- [x] Fix import of `particle_list.xml` (see [this failed job](https://travis-ci.com/github/redeboer/tensorwaves/jobs/321191484#L450))

**Comment by redeboer** [comment]
Codecov still missing in pull requests
