### ISSUE TITLE
Test formatting in Travis CI job

### ISSUE THREAD

**Issue by redeboer** [ComPWA/tensorwaves#24]
I understand the reasoning. Way out would be something like `requirements-devtools.txt`
```
autopep8==1.5
flake8==3.7.9
flake8-blind-except
flake8-builtins
flake8-docstrings
flake8-import-order
flake8-rst-docstrings
pep8-naming
pre-commit==2.2.0
pylint==2.4.4
tox==3.14.6
```
so that `tox.ini` can contain
```
[testenv:pep8]
passenv = PYTHONPATH
deps =
    -rrequirements-devtools.txt
commands =
    flake8
```
and then `requirements-dev.txt` would look like
```
-r doc/requirements.txt
-r tests/requirements.txt
-r requirements-devtools.txt
```
but I'm not sure if that's the way to go ^^

Maybe it's better to think about this later on once `tox` gets a more thorough implementation (i.e. if we have proper unit tests https://github.com/ComPWA/tensorwaves/issues/19). For the moment, the `tox.ini` file is really more of a placeholder for the `flake8` config (following [convention](https://flake8.pycqa.org/en/latest/user/configuration.html)) along with an elementary setup for `tox`.

_Originally posted by @redeboer in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMjU1Mzk3ODI0OnYy/pull_request_review_threads/more_comments_

**Comment by redeboer** [comment]
See also https://github.com/ComPWA/tensorwaves/pull/22 and https://github.com/ComPWA/tensorwaves/issues/19

**Comment by redeboer** [comment]
@spflueger 
I don't think it's a good idea to test the formatting in a travis job as this is already done through Codacy ([codacy.com/ComPWA/tensorwaves](https://app.codacy.com/gh/ComPWA/tensorwaves/])). The formatting checks that are installed through `requirements-dev.txt` are for local use, particularly at the moment when you commit. This forces the developer to incrementally improve the code quality prior to a PR.

**Comment by spflueger** [comment]
But we definitely need them in the CI. So our decision is between Codacy or Travis.
I guess for now we can stick with Codacy and we can always switch to something else later on.
For me the general way the requirements are currently setup is not ideal.
https://stackoverflow.com/questions/17803829/how-to-customize-a-requirements-txt-for-multiple-environments
I would follow this. So having requirements files for each environment
- ci/test
- prod
- dev

and reuse common dependencies across them. Then if you are a dev, you simply run the dev req and you are all setup and so on.

**Comment by spflueger** [comment]
I will close this issue, feel free to reopen if you think it needs more discussions

**Comment by redeboer** [comment]
Will be closed by https://github.com/ComPWA/tensorwaves/pull/26

Only thing I'm not sure about yet is whether Travis is that great for analysing formatting: it does not provide the nice graphical interface that something like Codacy provides and the only way to fix identified problems is through adding additional commits (no specific ignore buttons).
