### ISSUE TITLE
Speed up lambdifying

### ISSUE THREAD

**Issue by Leongrim** [ComPWA/tensorwaves#273]
A report on this issue is maintained here (https://github.com/ComPWA/compwa-org/pull/8):
https://compwa-org--8.org.readthedocs.build/reports/sympy/lambdify-speedup.html

---

Lambdifying a complex model takes a lot of time.
Here is a short example to reproduce this problem:

```
import qrules
import ampform
from ampform.dynamics.builder import (
    create_relativistic_breit_wigner_with_ff,
    create_non_dynamic_with_ff,
    create_non_dynamic
    
)
from tensorwaves.model import LambdifiedFunction, SympyModel

from tensorwaves.data.transform import HelicityTransformer
from time import time

result = qrules.generate_transitions(
    initial_state=("J/psi(1S)", [-1, +1]),
    final_state=["Sigma+", "K0", "p~"],
    allowed_intermediate_particles=["Sigma","N"],
    formalism_type="canonical-helicity",
    allowed_interaction_types="strong",
)
model_builder = ampform.get_builder(result)
model_no_dynamics = model_builder.generate()

for name in result.get_intermediate_particles().names:
    model_builder.set_dynamics(name, create_relativistic_breit_wigner_with_ff)
for initial_state in result.get_initial_state():
    model_builder.set_dynamics(initial_state.name, create_non_dynamic_with_ff)
model = model_builder.generate()

reaction_info = model.adapter.reaction_info
initial_state = next(iter(reaction_info.initial_state.values()))
print("Initial state:")
print(" ", initial_state.name)
print("Final state:")
for i, p in reaction_info.final_state.items():
    print(f"  {i}: {p.name}")

sympy_model = SympyModel(
    expression=model.expression,
    parameters=model.parameter_defaults,
)

def hms_string(sec_elapsed):
    h = int(sec_elapsed / (60 * 60))
    m = int((sec_elapsed % (60 * 60)) / 60)
    s = sec_elapsed % 60.
    return "{}h {:>02}min {:>05.2f}s".format(h, m, s)
start=time()
intensity = LambdifiedFunction(sympy_model, backend="numpy")
end=time()
print(f"building intensity took {hms_string(end-start)}")

```

**Comment by redeboer** [comment]
Thanks for the bug report @Leongrim!
As discussed, to close this issue, there are two approached worth considering:
1. Pickle a lambdified function with [`dill`](https://pypi.org/project/dill), so you at least don't have to re-lambdify the model each time. Unfortunately, it is however not (yet) possible to pickle functions lambdified to JAX, not even with `dill`.
2. Split up the lambdification process: take sub-trees of the model and lambdify those, then combine those partial functions (possibly using [`functools.partial`](https://docs.python.org/3/library/functools.html#functools.partial)). The approach would be a bit like that introduced by #247.

Both features would be nice to have, but will require more research. We can get back to this when there is more need for models that are as complicated as this.

**Comment by redeboer** [comment]
@Leongrim, #281 should close this issue. If you check out that branch, change:

```python
sympy_model = SympyModel(
    expression=model.expression,
    parameters=model.parameter_defaults,
)
```
to 

```python
sympy_model = SympyModel(
    expression=model.expression,
    parameters=model.parameter_defaults,
    max_complexity=True,
)
```
in the snippet you posted (https://github.com/ComPWA/tensorwaves/issues/273#issue-890236270).
