### ISSUE TITLE
Remove particle_list.yaml

### ISSUE THREAD

**Issue by spflueger** [ComPWA/tensorwaves#29]
There should be only a single source of truth. Also its harder to manage both.

Solution: drop one file and change the code appropriately. Here #13 is a required task, in which the expert system has to be decoupled from xml, in order to be able to drop one file.

**Comment by redeboer** [comment]
@spflueger Is a particle list still necessary if the particle info is embeded in the recipe file?

**Comment by spflueger** [comment]
No, I also think the recipe file provides this so they can be removed
