### ISSUE TITLE
Implement AIC and BIC

### ISSUE THREAD

**Issue by redeboer** [ComPWA/tensorwaves#290]

**Comment by redeboer** [comment]
I start to doubt now whether it makes sense to add these measures. Reason is that AIC and BIC are just [one of many criteria](https://en.wikipedia.org/wiki/Model_selection#Criteria) for selecting fit results and it is not the responsibility of TensorWaves to provide a selection of specific statistical techniques.

What could be provided is a way to count the number of degrees of freedom including the complex plane. That is more specific to optimization itself.

**Comment by Leongrim** [comment]
At least Tensorwaves should collect everything necessary in one place.
So it should be sufficient if the degrees of freedom and the number of events fitted are included in the fit result.
Than everything is in one place and the user doesn't has to collect it from many different objects.
This is at least my opinion and I know that it is trivial to calculate the number of fitted events.
