### ISSUE TITLE
Migrate expert system to separate repository

### ISSUE THREAD

**Issue by redeboer** [ComPWA/tensorwaves#57]
The expert system can function on its own, independent of an optimizer package (`tensorwaves`/`pycompwa`). It can even be used as a tool to check whether a decay is allowed.

- [x] Create new repository with the `tensorwaves.expertsystem` submodule only
- [x] Move expertsystem related issues from pycompwa to the new repo
- [x] Upload to PyPI
- [x] Remove `expertsystem` submodule
- [x] Add as dependency to `tensorwaves` and implement

**Comment by spflueger** [comment]
Sounds good! I added one more task

**Comment by redeboer** [comment]
Commits related to the expertsystem have been rebased and API interfaces to the expertsystem API now https://github.com/ComPWA/tensorwaves/commit/6c92ddf13fa083b10c39f759fc9e6571de3565d5#diff-684a0ceb2878d48b19612ca360e277efR91
