### ISSUE TITLE
Modify amplitude and kinematics modules so that they can handle the new recipe file structure

### ISSUE THREAD

**Issue by redeboer** [ComPWA/tensorwaves#77]
Follow-up to #74 
Required for #73 

The expertsystem v0.1.2a0 produces a slightly different amplitude model recipe file that the hard-coded `intensity-recipe.yaml` file.

**Comment by spflueger** [comment]
I believe this refers to the problem, that a predefined recipe structure is assumed in the kinematics code as well right?
